### PR TITLE
🐛 Make HC work without subscription

### LINKED ISSUE #25: Fix HC for PubSub non-consumers
When using FuQu PubSub for only producer adapter, it should not be required to have an existing subscription. The HC however checks if subscription is alive, causing it to fail. Implement static HC for producer-only FuQu PubSub instances or find a mechanism to test the topic is alive.

[Here](https://github.com/AckeeCZ/fuqu/blob/master/src/lib/adapters/pubsub.ts#L50) is the HC implementation.

1. HC call for subscription is implemented. Find a proper HC call for publisher (topic) and implement it.
2. PubSub instance must know it is a producer/consumer. It becomes a producer as soon as `publish` function is called, and consumer as soon as `subscribe` function is called. Keep this value in memory in the instance closure.
3. Update `isAlive` function accordingly to choose either of the function from 1, or both for producer-consumer.
4. It is possible that this bug required this [line](https://github.com/AckeeCZ/fuqu/blob/master/src/lib/adapters/index.test.ts#L91) in tests to pass. Remove it if it fixes the issue.

### PR DESCRIPTION
**Pull request by vlasy**
Resolves #25

### CODE REVIEW

File: src/lib/adapters/pubsub.ts [hunk 1]
```diff
@@ -33,26 +33,29 @@ export const fuQuPubSub: FuQuCreator<FuQuPubSubOptions, Message> = (pubSub: PubS
...
-            close: () => subscription.then(s => s.close()),
+            isAlive: () =>
+                subscription ? subscription.then((s) => s.isOpen) : topic.then((t) => t.get()).then((t) => !!t[0]),
+            close: () => (subscription ? subscription.then((s) => s.close()) : Promise.resolve()),
             publishJson: async (payload, attributes) => {
                 await (await topic).publishJSON(payload, attributes);
             },
-            registerHandler: async handler => {
+            registerHandler: async (handler) => {
+                subscription = topic.then((t) =>
```
Comment (smoliji) [inline src/lib/adapters/pubsub.ts]: This way we are creating a new subscription for each `handler` registration. I know it will probably get the instance from the remote, but why bother when we already have the subscription instance from the first call. What do you think?

Comment (vlasy) [reply src/lib/adapters/pubsub.ts]: Should be fixed in eaa72e2

Comment (smoliji) [reply src/lib/adapters/pubsub.ts]: Looks good

**Review by smoliji — APPROVED** [review]

**Review by smolijar — APPROVED** [review]
Thanks!
